# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22134995de95315ed2714ddae570c38d7dc1e83e89ce5e4fabfc30d5269a7d1d33ccb5d16c906a1ea60893857ed0cf98bc54ad427a65354e5fdd459d4616202e

test:
  secret_key_base: d8df169bceaeccbbe23b6c0679bfbd0feb58132c11e115554a4e0c19beac740c63007e915a504f5d365352d0da48fbc09ef654ad27e4dd810a11df81bebc4a70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
